### ISSUE TITLE
unable to import simiclasso submodules

### ISSUE THREAD

**Issue by bsierieb1** [jianhao2016/simicLASSO_git#3]
Hi,

I installed SimiC and its dependencies following the instructions in README. In python, I am able to `import simiclasso` but unable to import any of the submodules of simiclasso (the command line gets stuck on "In:"):
```
Python 3.7.10 (default, Jun  4 2021, 14:48:32) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from simiclasso.clus_regression import simicLASSO_op
In : 

```

I checked the python path and it does contain the path to simiclasso:
```
Python 3.7.10 (default, Jun  4 2021, 14:48:32) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.copy()
['', '/scratch/bs167/Work/project_scRNA-seq/2021.07.20_SimiC', '/ext3/miniconda3/envs/simic/lib/python3.7/site-packages', '/ext3/miniconda3/envs/simic/lib/python37.zip', '/ext3/miniconda3/envs/simic/lib/python3.7', '/ext3/miniconda3/envs/simic/lib/python3.7/lib-dynload', '/home/bs167/.local/lib/python3.7/site-packages', '/home/bs167/.local/lib/python3.7/site-packages/runner-0.0.0-py3.7.egg', '/ext3/miniconda3/envs/simic/lib/python3.7/site-packages/simiclasso-0.3.2-py3.7.egg']
>>> 
```

I suspect this has something to do with the fact that I have two versions of python - the default and the conda version, but I am not sure how to fix this. Thanks in advance for any advice!

**Comment by jianhao2016** [comment]
Hi bsireieb1, 

Thank you for your interest in our work! In the case of importing issues, I haven't seen this before, but can you try:

`from simiclasso import clus_regression`
and then use `clus_regression.simicLASSO_op`.  Another approach will be just to call the function by `simiclasso.clus_regression.simicLASSO_op`

Thanks.

**Comment by bsierieb1** [comment]
This does not work:
```
>>> import simiclasso
>>> simiclasso.clus_regression.simicLASSO_op
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'simiclasso' has no attribute 'clus_regression'
```

 It seems that none of the submodules of simiclasso are recognized:
```
>>> import simiclasso
>>> import inspect
>>> inspect.getmembers(simiclasso, inspect.ismodule)
[]
```

This is truly puzzling, since the submodules are definitely present in the `site-packages` directory:
```
(simic) Singularity> ls /ext3/miniconda3/envs/simic/lib/python3.7/site-packages/simiclasso-0.3.2-py3.7.egg/simiclasso/
__init__.py		    load_10x_data.py
__pycache__		    load_GSE_data.py
aver_clus_regression.py     load_mouse_data.py
calculate_smooth_matrix.py  magic_smooth.py
clus_regression.py	    sc_different_clustering.py
clus_regression_backup.py   sort_weight.py
clus_regression_mouse.py    visualization.py
common_io.py		    weighted_AUC_mat.py
direct_regression.py	    weighted_AUC_mat_all_target.py
dummy.py		    weighted_AUC_mat_intersected_targets.py
evaluation_metric.py	    weighted_AUC_mat_upper_cases.py
gene_id_to_name.py
```

**Comment by bsierieb1** [comment]
Ok, I installed a different python version and the import from simiclasso worked. However, `pip install -r requirements.txt` failed. First, it froze at `Building wheel for pandas (setup.py)`, then it threw a very long error message ending with:
```
error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pandas
```

I tried a few different python versions and here is the summary:
3.6.13 - import of simiclasso submodules fails - pip installation from requirements.txt works 
3.7.10 - import of simiclasso submodules fails - pip installation from requirements.txt works
3.8.10 - import of simiclasso submodules works - pip installation from requirements.txt fails
3.9.5 - import of simiclasso submodules works - pip installation from requirements.txt fails

Which python version are you using?

**Comment by bsierieb1** [comment]
I settled on python 3.9.5 and examined conflicts in the output of `conda install -c conda-forge --file requirements.txt`:
```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - cvxpy==1.0.10 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
  - ipdb==0.11 -> python[version='2.7.*|3.5.*|3.6.*']
  - matplotlib==3.0.2 -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
  - numpy==1.15.4 -> python[version='>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0']
  - pandas==0.25.1 -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
  - requests==2.21.0 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
  - scikit-learn==0.20.1 -> python[version='>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0']

Your python: python=3.9
```

Is python 3.6 the only python version that is compatible with `requirements.txt`?

In any case, I will proceed to `pip install` **most up-to-date versions** of the packages listed in `requirements.txt` under python 3.9.5 and see if this leads to any issues down the line...

**Comment by jianhao2016** [comment]
> I settled on python 3.9.5 and examined conflicts in the output of `conda install -c conda-forge --file requirements.txt`:
> 
> ```
> UnsatisfiableError: The following specifications were found
> to be incompatible with the existing python installation in your environment:
> 
> Specifications:
> 
>   - cvxpy==1.0.10 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
>   - ipdb==0.11 -> python[version='2.7.*|3.5.*|3.6.*']
>   - matplotlib==3.0.2 -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
>   - numpy==1.15.4 -> python[version='>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0']
>   - pandas==0.25.1 -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
>   - requests==2.21.0 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
>   - scikit-learn==0.20.1 -> python[version='>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0']
> 
> Your python: python=3.9
> ```
> 
> Is python 3.6 the only python version that is compatible with `requirements.txt`?
> 
In my testing environment, I use python 3.6 and 3.7 and both work fine. I haven't try 3.9 yet. According to your description, it seems like higher than 3.7 might not work with some of the dependent packages, but an updated version of them should work fine as well. Please continue with python 3.9 and the newer version of packase so that you can import the simic function and let me know if you have further questions.

**Comment by bsierieb1** [comment]
thanks, test data set ran ok!

the versions of python and installed packages:
```
(simic) Singularity> python -V
Python 3.9.5
(simic) Singularity> pip list
Package             Version
------------------- -------------------
argon2-cffi         20.1.0
async-generator     1.10
attrs               21.2.0
backcall            0.2.0
bleach              3.3.1
certifi             2021.5.30
cffi                1.14.6
charset-normalizer  2.0.3
cvxpy               1.1.13
cycler              0.10.0
debugpy             1.3.0
decorator           5.0.9
defusedxml          0.7.1
ecos                2.0.7.post1
entrypoints         0.3
idna                3.2
ipdb                0.13.9
ipykernel           6.0.3
ipython             7.25.0
ipython-genutils    0.2.0
ipywidgets          7.6.3
jedi                0.18.0
Jinja2              3.0.1
joblib              1.0.1
jsonschema          3.2.0
jupyter             1.0.0
jupyter-client      6.1.12
jupyter-console     6.4.0
jupyter-core        4.7.1
jupyterlab-pygments 0.1.2
jupyterlab-widgets  1.0.0
kiwisolver          1.3.1
MarkupSafe          2.0.1
matplotlib          3.4.2
matplotlib-inline   0.1.2
mistune             0.8.4
nbclient            0.5.3
nbconvert           6.1.0
nbformat            5.1.3
nest-asyncio        1.5.1
notebook            6.4.0
numpy               1.21.1
osqp                0.6.2.post0
packaging           21.0
pandas              1.3.0
pandocfilters       1.4.3
parso               0.8.2
pexpect             4.8.0
pickleshare         0.7.5
Pillow              8.3.1
pip                 21.1.3
prometheus-client   0.11.0
prompt-toolkit      3.0.19
ptyprocess          0.7.0
pycparser           2.20
Pygments            2.9.0
pyparsing           2.4.7
pyrsistent          0.18.0
python-dateutil     2.8.2
pytz                2021.1
pyzmq               22.1.0
qdldl               0.1.5.post0
qtconsole           5.1.1
QtPy                1.9.0
requests            2.26.0
scikit-learn        0.24.2
scipy               1.7.0
scs                 2.1.4
Send2Trash          1.7.1
setuptools          52.0.0.post20210125
simiclasso          0.3.2
six                 1.16.0
terminado           0.10.1
testpath            0.5.0
threadpoolctl       2.2.0
toml                0.10.2
tornado             6.1
traitlets           5.0.5
urllib3             1.26.6
wcwidth             0.2.5
webencodings        0.5.1
wheel               0.36.2
widgetsnbextension  3.5.1

```
